name: catbleh
description: catBleh. dumbass.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

  # allow custom window title bar 
  bitsdojo_window: ^0.1.1+1

  # advanced window effects that I don't think you can achieve with Dart because as far as I found, it doesn't control the windows
  #  so we have to modify the native [runner.cpp] or some other file
  flutter_acrylic: ^1.0.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

